apiVersion: v1
kind: Service
metadata:
 name: activemq
 namespace: kube-ops
spec:
 selector:
  app: activemq
 ports:
  - port: 8161
    targetPort: 8161
    protocol: TCP
    name: admin
    nodePort: 30004   
  - port: 61616
    targetPort: 61616
    protocol: TCP
    name: tcp
    nodePort: 30005   
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: activemq
 namespace: kube-ops
spec:
 replicas: 1
 selector:
  matchLabels:
    app: activemq
 template:
  metadata:
    labels:
     app: activemq
  spec:
   containers:
    - name: activemq
      image: webcenter/activemq
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: 8161
         protocol: TCP
       - containerPort: 61616
         protocol: TCP


