version: '3'
services:
    mysql:
        container_name: mysql
        network_mode: host
        volumes:
            - '$PWD/data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=123456
        image: 'mysql:5.7'